meower-media/client

src/screens/Sidebar.svelte
=> Fix issue #1

src/lib/Post.svelte
=> this helps with linebreaks in msgs

src/lib/Post.svelte, src/screens/Setup.svelte
parse "Webhooks" user. since the user parsed usually doesn't exist, the pfp is randomized.
=> Webhooks in Svelte

CONTRIBUTING.md, README.md
=> removed easter egg because im not funny

CONTRIBUTING.md, src/screens/Changelog.svelte, src/screens/Profile.svelte, src/screens/Setup.svelte
also update CONTRIBUTING.md to mention the branch naming scheme
=> Fix dango profile picture being duplicated when it is selected

CONTRIBUTING.md, README.md, src/screens/Changelog.svelte, src/screens/Profile.svelte, src/screens/Setup.svelte
=> Version 1.5.1

src/lib/modals/SetQuote.svelte
=> Correct the spelling of "publicly"

src/lib/Post.svelte, src/screens/Changelog.svelte, src/screens/Setup.svelte
Resolves #76 
...oops
(merging to master because it's urgent and there's stuff on develop)
=> Fix the image host whitelist not working

src/assets/style.css
Code stolen from BetterMeower™
=> `<hr>` improvements

src/lib/Post.svelte, src/screens/Changelog.svelte
=> Whitelist nextcloud.meower.org

.github/ISSUE_TEMPLATE/bug_report.md
Overlooked server template mentions, fixed
=> Fix bug report wording

src/lib/modals/ChangePassword.svelte, src/lib/modals/DeleteAccount.svelte, src/lib/modals/Login.svelte, src/lib/modals/Signup.svelte, src/screens/Changelog.svelte, src/screens/Setup.svelte
Require password confirmation on change password and delete account options. **Please do not merge until Mike has deployed the new server version.**
=> Change password and delete account password confirmation patch

src/lib/Modal.svelte, src/lib/Post.svelte, src/lib/TypingIndicator.svelte, src/screens/Home.svelte
- Better modal transition
- Fix typing indicator
- Some others
=> Add a few chnages

src/assets/style.css, src/lib/PFP.svelte, src/screens/Sidebar.svelte
=> Move some of the sidebar into a popup

src/lib/PostList.svelte
Should resolve https://github.com/meower-media-co/Meower-Svelte/pull/69#issuecomment-1477273311
Fixes some regressions from #58:
- Livechat join notifications appear in all group chats
- Group chat join notifications not appearing or being sent
=> Fix a few things with PostList

src/assets/style.css, src/screens/Groupchat.svelte
Resolves #95
(also hides the members list by default on mobile)
=> Make the members list fullscreen on mobile

src/screens/Home.svelte
=> prevent the ulist from taking up too much space

src/screens/Chatlist.svelte, src/screens/Settings.svelte
This PR will fix several issues with my last PR, and a couple of new changes.
✅ Finished
✅ Tested (works)
Summary: Changed the text of several elements of the UI as well as changed colors and punctuation fixes.
=> Grammatical Fixes and QOL #2

src/lib/ModPanel.svelte, src/screens/Home.svelte
Most people hate it. (only a few do not)
=> Revert #123

src/lib/ModPanel.svelte, src/screens/Home.svelte
This PR fixes bugs and improves the user experience.
=> Bug Fixes and QOL

src/lib/LiText.svelte, src/lib/Post.svelte, src/lib/ProfileView.svelte
in usernames, adds a slash through 0, adds serifs to uppercase i and adds a hook to lowercase L
urgent probably?
=> anti-impersonation in usernames

src/lib/ModPanel.svelte, src/screens/Home.svelte
=> Bring back user list in home

src/assets/style.css, src/lib/PostList.svelte, src/lib/stores.js, src/screens/Main.svelte, src/screens/Search.svelte, src/screens/SearchResults.svelte
Search!!! (I think this will make the client have full feature parity with vanilla, aside from some features nobody uses)
=> Add search

src/screens/Changelog.svelte
Final thing before 1.6 release!!
=> Add extra things to the changelog

src/assets/style.css, src/lib/Modal.svelte, src/screens/Groupchat.svelte
Add rounded corners to everything else because other people have found it a bit odd that only the containers are rounded.
=> Add rounded corners to everything else

index.html
Reverts meower-media-co/Meower-Svelte#166
=> Revert "Add announcement bar"

index.html, manifest/manifest.webmanifest, package-lock.json, package.json, src/App.svelte, src/assets/style.css, src/lib/Badge.svelte, src/lib/Container.svelte, src/lib/FormattedDate.svelte, src/lib/Member.svelte, src/lib/ModPanel.svelte, src/lib/Modal.svelte, src/lib/Post.svelte, src/lib/PostList.svelte, src/lib/modals/SwitchBGMSFX.svelte, src/lib/modals/SwitchTheme.svelte, src/screens/Home.svelte, src/screens/Profile.svelte, src/screens/Settings.svelte, src/screens/Setup.svelte, src/screens/Sidebar.svelte
Reverts meower-media-co/Meower-Svelte#171
=> Revert "done"

src/lib/Contributor.svelte, src/lib/Sidebar.svelte, src/pages/about.svelte
Because there are way too many people who stumble upon app.meower.org and don't know what it is. I think I did this in a few hours.
Things are subject to change, obviously. I don't have much idea on what else to add to this page (currently there's that part at the top, the 7 council members, a list of GH contributors and a special thanks section with trappist-1e), so I'm also looking for suggestions.
=> About page

CONTRIBUTING.md
this is such an annoying thing for me tbh
=> Fix CONTRIBUTING.MD

src/lib/modals/settings/SwitchBGMSFX.svelte, src/lib/modals/settings/SwitchTheme.svelte, src/pages/settings.svelte
Mainly for my additions to the client, requesting tnix here as i changed the settings code a bit
=> Fix some small issues with responsiveness

src/pages/about.svelte
=> zed asked for this

src/lib/CustomTheme.js, src/lib/clmanager.js, src/lib/modals/settings/CustomTheme.svelte
=> Fix: Remove crash on unknown theme version

src/lib/Post.svelte
Makes mentions actually work properly, and improves the confirmLink logic to not do hacky replacing. Not tested all that much.
=> Mention and link fixes

package-lock.json, package.json, src/lib/Setup.svelte, src/lib/clmanager.js, src/lib/modals/ConnectionFailed.svelte, src/lib/modals/Login.svelte, src/lib/modals/Signup.svelte, src/lib/modals/moderation/ModPanel.svelte, src/lib/modals/safety/ReportPost.svelte, src/lib/modals/safety/ReportUser.svelte, src/lib/modals/settings/ChangePassword.svelte, src/lib/modals/settings/DeleteAccount.svelte, src/lib/modals/settings/LogoutEverywhere.svelte
unblocks https://github.com/meower-media-co/Meower-Server/pull/243
=> api accounts support

src/pages/about.svelte
=> [1.9] Better changelog
